### PR TITLE
JupiterOne: Feature - New App - JupiterOne connector

### PR DESCRIPTION
**Pull request by austinkelleher**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [x] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [x] If this is a new connector or you are adding new actions
    - [x] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

The first release of the JupiterOne SOAR connector. The connector exposes a "Run Query" action for running JupiterOne queries (J1QL).

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by austinkelleher** [comment]
It's not clear to me how to fix the CI error. I looked at other connector projects and did not see any `repo_name_to_appid.json` file. Any feedback would be appreciated! 

```json
{
  "Repo Name Has Expected App Id": {
    "message": "Could not find an app id for jupiterone. Please add the app id for jupiterone to data/repo_name_to_appid.json",
    "success": false,
    "verbose": [
      "Could not find an app id for jupiterone. Please add the app id for jupiterone to data/repo_name_to_appid.json"
    ]
  }
}
```

**Comment by mattsayar-splunk** [comment]
Hey Austin, I emailed you about this earlier today, but to summarize here: we'll take care of it from here. We have to get Splunkbase ready for a net-new app.

**Comment by mishalp-crest** [comment]
@austinkelleher, Could you please provide write access as there are pre-commit changes that need to be fixed?

**Comment by austinkelleher** [comment]
@mishalp-crest I don't have write access to this repo currently. You could open a PR against my branch on the JupiterOne fork and I could merge it into my branch. See: https://github.com/JupiterOne/splunk-soar-connector-jupiterone/tree/INT-3633-splunk-app

**Comment by mattsayar-splunk** [comment]
Hey @austinkelleher I've added you as a Maintainer to this repo

**Comment by austinkelleher** [comment]
@mattsayar-splunk it looks like another build was triggered and the tests are now passing! Were there changes that you made on your end?

**Comment by mishalp-crest** [comment]
Hello @austinkelleher 
We have taken (copied)  the branch from the JupiterOne repo and done the required changes in the SOAR repo branch 
(Ref.: [INT-3633-splunk-app-from-contri-repo](https://github.com/splunk-soar-connectors/jupiterone/tree/INT-3633-splunk-app-from-contri-repo)).
This PR https://github.com/splunk-soar-connectors/jupiterone/pull/2 has all the changes.
so, we are going to use it to release the app

Let us know if you have any doubts/concerns?

**Comment by mattsayar-splunk** [comment]
Looks like Mishal has you all squared away

**Pull request merged**
